language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

stages:
  - psalm analysis
  - test
  - coverage analysis
  - security checker

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  
script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: psalm analysis
      php: '7.3'
      script:
        - vendor/bin/psalm
    - stage: coverage analysis
      php: '7.3'
      env: XDEBUG="true"
      install:
        - composer require --dev php-coveralls/php-coveralls
        - mkdir -p build/logs
      script:
        - vendor/bin/phpunit -c phpunit.xml.dist
      after_success:
        - travis_retry php vendor/bin/php-coveralls -v
    - stage: security checker
      php: '7.3'
      install:
        - composer require --dev sensiolabs/security-checker
      script:
        - vendor/bin/security-checker security:check